In [19]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [20]:
def f(theta,y,F) :
    return (((F*np.cos(theta))/(m2+(m1*(np.sin(theta))**2)))-((m1*(y**2)*(np.sin(theta))**2)/(2*R*(m2+(m1*(np.sin(theta)**2)))))-(((m1+m2)*g*np.sin(theta))/(m2+(m1*(np.sin(theta))**2))))

def f_2(theta,csi,F):
    return f(theta,R*F*csi,F)/((F**2)*R)

In [21]:
""""50
t_fin=2.5
h=t_fin/n
theta0=0
csi0=0
t0=0
m1=0.1
m2=0.75
g=0

theta=theta0
csi=csi0
t=t0
F=6
R=0.3
T=np.empty(n)
Y=np.empty(n)

for i in range (n):
    theta_i=theta
    csi_i=csi
    t_i=t
    T[i]=t_i
    Y[i]=R*F*csi_i
    


    K1 = h*csi
    M1 = h*f_2(theta,csi)

    K2 = h*(csi+M1/2)
    M2 = h*f_2(theta+(K1/2), csi+(M1/2))
         
    K3 = h*(csi+(M2/2))
    M3 = h*f_2(theta+(K2/2),csi+(M2/2))
         
    K4 = h*(csi+(M3/2))
    M4 = h*f_2(theta+K3 , csi+M3)
             
        
 
    theta = theta + (K1/6)+(K2/3)+(K3/3)+(K4/6)
    csi = csi+(M1/6)+(M2/3)+(M3/3)+(M4/6)
    
    t = t+h""

SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-21-7740c4bfd669>, line 45)

In [40]:
R=0.3
theta0=0
csi0=0
t0=0
m1=0.1
m2=0.75
g=0

n=10
def RK4(F,g):
    t_fin=2.5
    h=t_fin/n
    theta=theta0
    csi=csi0
    t=t0
    R=0.3
    T=np.empty(n)
    Y=np.empty(n)

    for i in range (n):
        theta_i=theta
        csi_i=csi
        t_i=t
        T[i]=t_i
        Y[i]=R*F*csi_i
    


        K1 = h*csi
        M1 = h*f_2(theta,csi,F)

        K2 = h*(csi+M1/2)
        M2 = h*f_2(theta+(K1/2), csi+(M1/2),F)
         
        K3 = h*(csi+(M2/2))
        M3 = h*f_2(theta+(K2/2),csi+(M2/2),F)
         
        K4 = h*(csi+(M3/2))
        M4 = h*f_2(theta+K3 , csi+M3, F)
             
        
 
        theta = theta + (K1/6)+(K2/3)+(K3/3)+(K4/6)
        csi = csi+(M1/6)+(M2/3)+(M3/3)+(M4/6)
        t = t+h
        
    return T, Y

In [41]:
RK4(6,0)


(array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25]),
 array([0.        , 0.33330495, 0.66600811, 0.9949207 , 1.31146091,
        1.59970594, 1.83759944, 2.00305151, 2.08210044, 2.07266135]))

In [42]:
RK4(22,0)

(array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25]),
 array([0.        , 0.33333123, 0.66661811, 0.99962776, 1.33172993,
        1.6616798 , 1.98740336, 2.30581221, 2.61269628, 2.90276027]))